
schemaName: sharding_db

dataSourceCommon:
 username: root
 password: 
 connectionTimeoutMilliseconds: 30000
 idleTimeoutMilliseconds: 60000
 maxLifetimeMilliseconds: 1800000
 maxPoolSize: 5
 minPoolSize: 1
 maintenanceIntervalMilliseconds: 30000

dataSources:
 db_0:
   url: jdbc:mysql://127.0.0.1:3306/db_0?serverTimezone=UTC&useSSL=false
 db_1:
   url: jdbc:mysql://127.0.0.1:3306/db_1?serverTimezone=UTC&useSSL=false

rules:
- !SHARDING
 tables:
   order:
     actualDataNodes: db_${0..1}.order_${0..1}
     tableStrategy:
       standard:
         shardingColumn: order_id
         shardingAlgorithmName: order_inline
     keyGenerateStrategy:
       column: order_id
       keyGeneratorName: snowflake
 bindingTables:
   - order
 defaultDatabaseStrategy:
   standard:
     shardingColumn: user_id
     shardingAlgorithmName: database_inline
 defaultTableStrategy:
   none:
 
 shardingAlgorithms:
   database_inline:
     type: INLINE
     props:
       algorithm-expression: db_${user_id % 2}
   order_inline:
     type: INLINE
     props:
       algorithm-expression: order_${order_id % 2}
 keyGenerators:
   snowflake:
     type: SNOWFLAKE
     props:
       worker-id: 123
